"""Every directory the modelling code reads or writes, defined once.

Paths are resolved from this file, so they hold no matter where a notebook kernel,
the test runner or the inference service was started.
"""

from pathlib import Path

MODEL_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = MODEL_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"              # source datasets, never modified
PROCESSED_DATA_DIR = DATA_DIR / "processed"  # derived datasets, regenerated by code

ARTIFACTS_DIR = MODEL_DIR / "artifacts"      # trained pipelines, metrics, plots
LOGS_DIR = MODEL_DIR / "logs"
NOTEBOOKS_DIR = MODEL_DIR / "notebooks"
